name: .NET

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-2019
    steps:
      - name: checkout
        uses: actions/checkout@v1
      - name: Build DotNET35
        run: |
           cd $Env:GITHUB_WORKSPACE
           NuGet restore
           cd "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\MSBuild\Current\Bin\"
           .\MSBuild.exe $Env:GITHUB_WORKSPACE\Verademo-dotnet.sln
      - name: ZIP
        run: |
           cd $Env:GITHUB_WORKSPACE\Verademo-Dotnet\bin\
           7z a -r verademoDotNet.zip *
      - name: Publicando Artefato
        uses: actions/upload-artifact@v2
        with:
          name: pacoteVeracode
          path: $Env:GITHUB_WORKSPACE\Verademo-Dotnet\bin\verademoDotNet.zip

  Veracode_SAST:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode
      - uses: veracode/veracode-uploadandscan-action@master # Faz a analise da Veracode
        env:
          VID: ${{ secrets.VID }} # Lembrar de criar as credenciais no Secrets
          VKEY: ${{ secrets.VKEY }}
          AppName: VeraDemoDotNet
        with:
          vid: '$VID'
          vkey: '$VKEY'
          criticality: 'VeryHigh'
          appname: '$AppName'
          createsandbox: true
          filepath: 'verademoDotNet.zip'
          deleteIncompleteScan: false
          version: ${{ github.run_id }}

  Veracode_PipelineScan:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download Artefato
        uses: actions/download-artifact@v2
        with:
          name: pacoteVeracode
      - name: Veracode Pipeline Scan
        env:
          VID: ${{ secrets.VID }} # Lembrar de criar as credenciais no Secrets
          VKEY: ${{ secrets.VKEY }}
          CaminhoArquivo: './verademoDotNet.zip'
        run: |
          curl -sSO https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
          unzip pipeline-scan-LATEST.zip
          java -jar pipeline-scan.jar -vid $VID -vkey $VKEY -f $CaminhoArquivo